import React, { useState } from 'react';
import Seo from '../components/Seo';

const apiUrl = process.env.REACT_APP_EMAIL_SERVER_URL || '';

export default function AdmissionStatus() {
  const [form, setForm] = useState({ reference: '', email: '' }); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); setResult(null); try { if (!apiUrl) throw new Error('The admissions status service is not configured yet.'); const response = await fetch(`${apiUrl}/api/admissions/status`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Lookup failed.'); setResult(data); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  return <><Seo title="Check Admission Status | Dankamf Educational Complex" description="Check the status of your Dankamf Educational Complex admission application." /><main className="min-h-screen bg-background-alt px-4 py-12 sm:px-8"><div className="mx-auto max-w-xl text-center"><p className="text-xs font-black uppercase tracking-[0.25em] text-accent">Admissions</p><h1 className="mt-3 text-4xl font-black text-primary sm:text-5xl">Check Application Status</h1><p className="mt-4 text-text-light">Use your application reference and the email address submitted with your application.</p><form onSubmit={submit} className="mt-8 space-y-4 rounded-xl border border-slate-200 bg-white p-5 text-left shadow-sm sm:p-8"><input required value={form.reference} onChange={(e) => setForm({ ...form, reference: e.target.value })} placeholder="DKE-2026-ABC123" className="w-full rounded-lg border p-3 uppercase" /><input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="Application email address" className="w-full rounded-lg border p-3" /><button disabled={loading} className="w-full rounded-full bg-primary px-6 py-3 font-bold text-white hover:bg-primary-dark disabled:opacity-60">{loading ? 'Checking…' : 'Check Status'}</button>{error && <p role="alert" className="text-sm font-semibold text-red-600">{error}</p>}{result && <div className="rounded-lg bg-blue-50 p-4 text-sm text-primary"><p className="font-bold">{result.studentName}</p><p>{result.programme}</p><p className="mt-2 text-lg font-black capitalize">Status: {result.status}</p></div>}</form></div></main></>;
}
