import React, { useState } from 'react';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase/config';
import Seo from '../components/Seo';

export default function Alumni() {
  const [form, setForm] = useState({ name: '', email: '', graduationYear: '', programme: '', phone: '', interest: '' }); const [status, setStatus] = useState(''); const [saving, setSaving] = useState(false);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await addDoc(collection(db, 'alumniRegistrations'), { ...form, createdAt: serverTimestamp() }); setForm({ name: '', email: '', graduationYear: '', programme: '', phone: '', interest: '' }); setStatus('Thank you. Your alumni registration has been received.'); } catch (error) { console.error(error); setStatus('Registration failed. Please try again.'); } finally { setSaving(false); } };
  return <><Seo title="Alumni | Dankamf Educational Complex" description="Reconnect with the Dankamf Educational Complex alumni community." /><main className="min-h-screen bg-background-alt"><section className="bg-primary-dark px-4 py-14 text-center text-white sm:px-8"><p className="text-xs font-black uppercase tracking-[0.25em] text-accent-yellow">The Dankamf Community</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Alumni Network</h1><p className="mx-auto mt-4 max-w-2xl text-slate-300">Reconnect, share your journey, and help shape the future of the Dankamf family.</p></section><section className="px-4 py-12 sm:px-8"><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><h2 className="text-3xl font-black text-primary">Stay Connected</h2><p className="mt-4 leading-relaxed text-text-light">Register your details to hear about alumni events, opportunities, success stories, and ways to support current learners.</p><div className="mt-6 space-y-3 text-sm text-text-light"><p><strong className="text-darkgray">Alumni events:</strong> Reunions, mentorship, and community gatherings.</p><p><strong className="text-darkgray">Give back:</strong> Support scholarships, learning, and student development.</p><p><strong className="text-darkgray">Share your story:</strong> Inspire the next generation of Dankamf learners.</p></div></div><form onSubmit={submit} className="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 sm:p-7"><input required name="name" value={form.name} onChange={update} placeholder="Full name" className="rounded-lg border p-3" /><input required type="email" name="email" value={form.email} onChange={update} placeholder="Email address" className="rounded-lg border p-3" /><input name="graduationYear" value={form.graduationYear} onChange={update} placeholder="Graduation year" className="rounded-lg border p-3" /><input name="programme" value={form.programme} onChange={update} placeholder="Programme or class" className="rounded-lg border p-3" /><input name="phone" value={form.phone} onChange={update} placeholder="Phone number" className="rounded-lg border p-3 sm:col-span-2" /><textarea name="interest" value={form.interest} onChange={update} placeholder="How would you like to stay involved?" rows="4" className="rounded-lg border p-3 sm:col-span-2" /><button disabled={saving} className="rounded-full bg-accent-yellow px-6 py-3 font-bold text-darkgray hover:bg-accent-yellow-dark disabled:opacity-60 sm:col-span-2">{saving ? 'Registering…' : 'Join the Alumni Network'}</button>{status && <p role="status" className="text-center text-sm font-semibold text-primary sm:col-span-2">{status}</p>}</form></div></section></main></>;
}
