import React, { useState } from 'react';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase/config';
import Seo from '../components/Seo';

export default function BookTour() {
  const [form, setForm] = useState({ name: '', email: '', phone: '', preferredDate: '', message: '' });
  const [status, setStatus] = useState(''); const [saving, setSaving] = useState(false);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); setStatus(''); try { await addDoc(collection(db, 'contactForms'), { ...form, type: 'campus-tour', message: form.message || 'Campus tour request', timestamp: serverTimestamp() }); setForm({ name: '', email: '', phone: '', preferredDate: '', message: '' }); setStatus('Thank you. Our admissions team will confirm your campus tour shortly.'); } catch (error) { console.error(error); setStatus('We could not submit your request. Please try again.'); } finally { setSaving(false); } };
  return <><Seo title="Book a Campus Tour | Dankamf Educational Complex" description="Arrange a visit to Dankamf Educational Complex." /><main className="min-h-screen bg-background-alt px-4 py-12 sm:px-8"><div className="mx-auto max-w-2xl"><div className="mb-8 text-center"><p className="text-xs font-black uppercase tracking-[0.25em] text-accent">Visit Dankamf</p><h1 className="mt-3 text-4xl font-black text-primary sm:text-5xl">Book a Campus Tour</h1><p className="mt-4 text-text-light">See our learning environment, meet our team, and discover the Dankamf difference.</p></div><form onSubmit={submit} className="grid gap-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 sm:p-8"><label className="space-y-2"><span className="text-sm font-bold text-darkgray">Your name</span><input required name="name" value={form.name} onChange={update} className="w-full rounded-lg border border-slate-300 p-3 focus:ring-2 focus:ring-primary" /></label><label className="space-y-2"><span className="text-sm font-bold text-darkgray">Preferred date</span><input required type="date" name="preferredDate" value={form.preferredDate} onChange={update} className="w-full rounded-lg border border-slate-300 p-3 focus:ring-2 focus:ring-primary" /></label><label className="space-y-2"><span className="text-sm font-bold text-darkgray">Email address</span><input required type="email" name="email" value={form.email} onChange={update} className="w-full rounded-lg border border-slate-300 p-3 focus:ring-2 focus:ring-primary" /></label><label className="space-y-2"><span className="text-sm font-bold text-darkgray">Phone number</span><input required type="tel" name="phone" value={form.phone} onChange={update} className="w-full rounded-lg border border-slate-300 p-3 focus:ring-2 focus:ring-primary" /></label><label className="space-y-2 sm:col-span-2"><span className="text-sm font-bold text-darkgray">What would you like to discuss?</span><textarea name="message" value={form.message} onChange={update} rows="4" className="w-full rounded-lg border border-slate-300 p-3 focus:ring-2 focus:ring-primary" /></label><div className="sm:col-span-2"><button disabled={saving} className="w-full rounded-full bg-accent-yellow px-6 py-3 font-bold text-darkgray hover:bg-accent-yellow-dark disabled:opacity-60">{saving ? 'Sending request…' : 'Request a Tour'}</button>{status && <p role="status" className="mt-4 text-center text-sm font-semibold text-primary">{status}</p>}</div></form></div></main></>;
}
