import React, { useEffect, useState } from 'react';
import { collection, getDocs, orderBy, query } from 'firebase/firestore';
import { db } from '../firebase/config';
import Seo from '../components/Seo';
import LoadingSpinner from '../components/LoadingSpinner';

export default function Fees() {
  const [fees, setFees] = useState([]); const [scholarships, setScholarships] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([getDocs(query(collection(db, 'admissionFees'), orderBy('programme', 'asc'))), getDocs(query(collection(db, 'scholarships'), orderBy('createdAt', 'desc')))]).then(([feeSnap, scholarshipSnap]) => { setFees(feeSnap.docs.map((item) => item.data())); setScholarships(scholarshipSnap.docs.map((item) => item.data()).filter((item) => item.published)); }).catch(console.error).finally(() => setLoading(false)); }, []);
  return <><Seo title="Fees & Scholarships | Dankamf Educational Complex" description="Review admission fees and scholarship information for Dankamf Educational Complex." /><main className="min-h-screen bg-background-alt"><section className="bg-primary-dark px-4 py-14 text-center text-white sm:px-8"><p className="text-xs font-black uppercase tracking-[0.25em] text-accent-yellow">Admissions Finance</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Fees & Scholarships</h1><p className="mx-auto mt-4 max-w-2xl text-slate-300">Current fee information and support options for families.</p></section><section className="mx-auto max-w-6xl px-4 py-12 sm:px-8">{loading ? <LoadingSpinner label="Loading fees" /> : fees.length === 0 ? <p className="text-center text-text-light">Fee information will be published soon. Please contact admissions for guidance.</p> : <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full"><thead className="bg-blue-50"><tr>{['Programme', 'Admission', 'Tuition', 'Stationery'].map((heading) => <th key={heading} className="px-5 py-4 text-left text-sm font-black text-primary">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{fees.map((fee) => <tr key={fee.programme}><td className="px-5 py-4 font-bold text-darkgray">{fee.programme}</td><td className="px-5 py-4">{fee.admission || '—'}</td><td className="px-5 py-4">{fee.tuition || '—'}</td><td className="px-5 py-4">{fee.stationery || '—'}</td></tr>)}</tbody></table></div>}<div className="mt-8 rounded-xl border border-blue-200 bg-blue-50 p-6"><h2 className="text-2xl font-black text-primary">Scholarship Information</h2>{scholarships.length ? <div className="mt-4 space-y-3">{scholarships.map((item) => <div key={item.title}><h3 className="font-bold text-primary">{item.title}</h3><p className="mt-1 text-text-light">{item.description}</p></div>)}</div> : <p className="mt-3 leading-relaxed text-text-light">For scholarship opportunities, eligibility, and payment plans, please contact the admissions office directly.</p>}</div></section></main></>;
}
