import React, { useState } from 'react';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase/config';
import Seo from '../components/Seo';

export default function InterviewBooking() {
  const [form, setForm] = useState({ reference: '', name: '', email: '', phone: '', preferredDate: '', preferredTime: '' }); const [status, setStatus] = useState(''); const [saving, setSaving] = useState(false);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await addDoc(collection(db, 'interviewRequests'), { ...form, status: 'new', createdAt: serverTimestamp() }); setForm({ reference: '', name: '', email: '', phone: '', preferredDate: '', preferredTime: '' }); setStatus('Interview request received. Admissions will confirm your appointment.'); } catch (error) { console.error(error); setStatus('Unable to submit your request. Please try again.'); } finally { setSaving(false); } };
  return <><Seo title="Book an Admissions Interview | Dankamf Educational Complex" description="Request an admissions interview at Dankamf Educational Complex." /><main className="min-h-screen bg-background-alt px-4 py-12 sm:px-8"><div className="mx-auto max-w-2xl"><div className="mb-8 text-center"><p className="text-xs font-black uppercase tracking-[0.25em] text-accent">Admissions</p><h1 className="mt-3 text-4xl font-black text-primary sm:text-5xl">Book an Interview</h1><p className="mt-4 text-text-light">Choose a convenient time and our admissions team will confirm availability.</p></div><form onSubmit={submit} className="grid gap-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 sm:p-8"><input required name="reference" value={form.reference} onChange={update} placeholder="Application reference" className="rounded-lg border p-3 sm:col-span-2" /><input required name="name" value={form.name} onChange={update} placeholder="Parent/guardian name" className="rounded-lg border p-3" /><input required type="email" name="email" value={form.email} onChange={update} placeholder="Email address" className="rounded-lg border p-3" /><input required type="tel" name="phone" value={form.phone} onChange={update} placeholder="Phone number" className="rounded-lg border p-3 sm:col-span-2" /><label className="space-y-2"><span className="text-sm font-bold text-darkgray">Preferred date</span><input required type="date" name="preferredDate" value={form.preferredDate} onChange={update} className="w-full rounded-lg border p-3" /></label><label className="space-y-2"><span className="text-sm font-bold text-darkgray">Preferred time</span><input required type="time" name="preferredTime" value={form.preferredTime} onChange={update} className="w-full rounded-lg border p-3" /></label><button disabled={saving} className="rounded-full bg-accent-yellow px-6 py-3 font-bold text-darkgray hover:bg-accent-yellow-dark disabled:opacity-60 sm:col-span-2">{saving ? 'Submitting…' : 'Request Interview'}</button>{status && <p role="status" className="text-center text-sm font-semibold text-primary sm:col-span-2">{status}</p>}</form></div></main></>;
}
