import React, { useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp } from 'firebase/firestore';
import { deleteObject, getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { useParams } from 'react-router-dom';
import { db, storage } from '../../firebase/config';
import AdminLayout from '../../components/AdminLayout';
import PageTitle from '../../components/PageTitle';
import LoadingSpinner from '../../components/LoadingSpinner';

export default function ApplicationDocuments() {
  const { applicationId } = useParams(); const [application, setApplication] = useState(null); const [documents, setDocuments] = useState([]); const [file, setFile] = useState(null); const [label, setLabel] = useState('Birth Certificate'); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = async () => { const applicationSnap = await getDocs(query(collection(db, 'admissionApplications'))); const found = applicationSnap.docs.find((item) => item.id === applicationId); setApplication(found ? found.data() : null); const docsSnap = await getDocs(query(collection(db, `admissionApplications/${applicationId}/documents`), orderBy('createdAt', 'desc'))); setDocuments(docsSnap.docs.map((item) => ({ id: item.id, ...item.data() }))); setLoading(false); };
  useEffect(() => { load().catch((error) => { console.error(error); setMessage('Unable to load application documents.'); setLoading(false); }); }, [applicationId]);
  const upload = async (event) => { event.preventDefault(); if (!file) return; setSaving(true); setMessage(''); try { const path = `admissionDocuments/${applicationId}/${Date.now()}-${file.name}`; const uploaded = await uploadBytes(ref(storage, path), file); const url = await getDownloadURL(uploaded.ref); await addDoc(collection(db, `admissionApplications/${applicationId}/documents`), { label, fileName: file.name, url, storagePath: path, createdAt: serverTimestamp() }); setFile(null); event.target.reset(); setMessage('Document uploaded.'); await load(); } catch (error) { console.error(error); setMessage('Document upload failed.'); } finally { setSaving(false); } };
  const remove = async (item) => { if (!window.confirm(`Delete ${item.fileName}?`)) return; await deleteDoc(doc(db, `admissionApplications/${applicationId}/documents`, item.id)); if (item.storagePath) await deleteObject(ref(storage, item.storagePath)); setDocuments((items) => items.filter((entry) => entry.id !== item.id)); };
  if (loading) return <AdminLayout><LoadingSpinner label="Loading documents" /></AdminLayout>;
  return <AdminLayout><PageTitle>Application Documents</PageTitle>{application && <p className="mt-2 text-sm text-slate-600">{application.studentName} · {application.applicationReference || 'No reference'}</p>}<form onSubmit={upload} className="mt-5 flex max-w-3xl flex-col gap-3 rounded-xl border border-slate-200 bg-white p-5 sm:flex-row sm:items-end"><label className="flex-1 space-y-2"><span className="text-sm font-bold">Document type</span><select value={label} onChange={(e) => setLabel(e.target.value)} className="w-full rounded-lg border p-3"><option>Birth Certificate</option><option>Previous School Report</option><option>Passport Photo</option><option>Medical Record</option><option>Other</option></select></label><label className="flex-1 space-y-2"><span className="text-sm font-bold">File</span><input required type="file" onChange={(e) => setFile(e.target.files[0])} className="w-full rounded-lg border p-2.5 text-sm" /></label><button disabled={saving} className="rounded-full bg-primary px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Uploading…' : 'Upload'}</button></form>{message && <p className="mt-3 text-sm font-semibold text-primary">{message}</p>}<div className="mt-6 space-y-3">{documents.length === 0 ? <p className="text-slate-500">No documents uploaded.</p> : documents.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div><p className="font-bold text-primary">{item.label}</p><p className="text-sm text-slate-500">{item.fileName}</p></div><div className="space-x-4 text-sm"><a href={item.url} target="_blank" rel="noreferrer" className="font-bold text-primary">View</a><button onClick={() => remove(item)} className="font-bold text-red-600">Delete</button></div></div>)}</div></AdminLayout>;
}
