import React, { useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp } from 'firebase/firestore';
import { getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { FaDownload, FaTrash } from 'react-icons/fa';
import { db, storage } from '../../firebase/config';
import { useAuth } from '../../context/AuthContext';
import { logActivity } from '../../utils/activityLog';
import AdminLayout from '../../components/AdminLayout';
import PageTitle from '../../components/PageTitle';
import LoadingSpinner from '../../components/LoadingSpinner';

export default function ManageDownloads() {
  const { user } = useAuth();
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const [form, setForm] = useState({ title: '', category: 'Prospectus', file: null, published: true });
  const load = () => getDocs(query(collection(db, 'downloads'), orderBy('createdAt', 'desc'))).then((snap) => setItems(snap.docs.map((item) => ({ id: item.id, ...item.data() })))).catch(console.error).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); if (!form.file) return setMessage('Choose a file to upload.'); setSaving(true); setMessage(''); try { const fileRef = ref(storage, `downloads/${Date.now()}-${form.file.name}`); const uploaded = await uploadBytes(fileRef, form.file); const url = await getDownloadURL(uploaded.ref); await addDoc(collection(db, 'downloads'), { title: form.title, category: form.category, fileName: form.file.name, url, published: form.published, createdAt: serverTimestamp() }); await logActivity(user, 'add_download', `Uploaded resource: "${form.title}"`); setForm({ title: '', category: 'Prospectus', file: null, published: true }); setMessage('Resource uploaded successfully.'); await load(); } catch (error) { console.error(error); setMessage('Upload failed. Please try again.'); } finally { setSaving(false); } };
  const remove = async (item) => { if (!window.confirm(`Delete “${item.title}”?`)) return; await deleteDoc(doc(db, 'downloads', item.id)); setItems((current) => current.filter((entry) => entry.id !== item.id)); };
  return <AdminLayout><PageTitle>Download Center</PageTitle><form onSubmit={submit} className="mt-5 grid max-w-3xl gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2"><label className="space-y-2 sm:col-span-2"><span className="text-sm font-bold text-darkgray">Resource title</span><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="w-full rounded-lg border border-slate-300 p-3 focus:ring-2 focus:ring-primary" /></label><label className="space-y-2"><span className="text-sm font-bold text-darkgray">Category</span><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="w-full rounded-lg border border-slate-300 bg-white p-3"><option>Prospectus</option><option>Admission Forms</option><option>School Calendar</option><option>Policies</option><option>Holiday Lists</option><option>Reading Lists</option></select></label><label className="space-y-2"><span className="text-sm font-bold text-darkgray">File</span><input required type="file" onChange={(e) => setForm({ ...form, file: e.target.files[0] })} className="w-full rounded-lg border border-slate-300 p-2.5 text-sm" /></label><button disabled={saving} className="rounded-full bg-primary px-6 py-3 text-sm font-bold text-white hover:bg-primary-dark disabled:opacity-60 sm:col-span-2">{saving ? 'Uploading…' : 'Upload Resource'}</button>{message && <p className="text-sm font-semibold text-primary sm:col-span-2">{message}</p>}</form><div className="mt-6 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <LoadingSpinner label="Loading downloads" /> : <table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{['Resource', 'Category', 'File', 'Actions'].map((heading) => <th key={heading} className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{items.length === 0 ? <tr><td colSpan="4" className="p-8 text-center text-slate-500">No resources uploaded.</td></tr> : items.map((item) => <tr key={item.id}><td className="px-5 py-4 font-bold text-darkgray">{item.title}</td><td className="px-5 py-4 text-sm">{item.category}</td><td className="px-5 py-4 text-sm text-slate-500">{item.fileName}</td><td className="px-5 py-4"><a href={item.url} target="_blank" rel="noreferrer" className="mr-4 inline-flex items-center gap-1 text-primary"><FaDownload /> View</a><button onClick={() => remove(item)} className="inline-flex items-center gap-1 text-red-600"><FaTrash /> Delete</button></td></tr>)}</tbody></table>}</div></AdminLayout>;
}
