import React, { useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp } from 'firebase/firestore';
import { db } from '../../firebase/config';
import AdminLayout from '../../components/AdminLayout';
import PageTitle from '../../components/PageTitle';
import LoadingSpinner from '../../components/LoadingSpinner';

export default function ManageLeadership() {
  const [leaders, setLeaders] = useState([]); const [loading, setLoading] = useState(true); const [form, setForm] = useState({ name: '', role: '', bio: '', imageUrl: '', order: 1, published: true });
  const load = () => getDocs(query(collection(db, 'leadership'), orderBy('order', 'asc'))).then((snap) => setLeaders(snap.docs.map((item) => ({ id: item.id, ...item.data() })))).catch(console.error).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const add = async (event) => { event.preventDefault(); await addDoc(collection(db, 'leadership'), { ...form, order: Number(form.order), createdAt: serverTimestamp() }); setForm({ name: '', role: '', bio: '', imageUrl: '', order: 1, published: true }); load(); };
  const remove = async (id) => { if (!window.confirm('Delete this leadership profile?')) return; await deleteDoc(doc(db, 'leadership', id)); setLeaders((items) => items.filter((item) => item.id !== id)); };
  return <AdminLayout><PageTitle>Leadership Team</PageTitle><form onSubmit={add} className="mt-5 grid max-w-3xl gap-4 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-2"><input required placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-lg border p-3" /><input required placeholder="Role" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="rounded-lg border p-3" /><input placeholder="Photo URL" value={form.imageUrl} onChange={(e) => setForm({ ...form, imageUrl: e.target.value })} className="rounded-lg border p-3 sm:col-span-2" /><textarea required placeholder="Biography" value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} rows="4" className="rounded-lg border p-3 sm:col-span-2" /><input type="number" min="1" placeholder="Display order" value={form.order} onChange={(e) => setForm({ ...form, order: e.target.value })} className="rounded-lg border p-3" /><button className="rounded-full bg-primary px-5 py-3 font-bold text-white hover:bg-primary-dark">Add Profile</button></form><div className="mt-6 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <LoadingSpinner label="Loading leadership" /> : <table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{['Name', 'Role', 'Published', 'Actions'].map((heading) => <th key={heading} className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{leaders.map((leader) => <tr key={leader.id}><td className="px-5 py-4 font-bold">{leader.name}</td><td className="px-5 py-4 text-sm">{leader.role}</td><td className="px-5 py-4 text-sm">{leader.published ? 'Yes' : 'No'}</td><td className="px-5 py-4"><button onClick={() => remove(leader.id)} className="font-bold text-red-600">Delete</button></td></tr>)}</tbody></table>}</div></AdminLayout>;
}
