import React, { useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp } from 'firebase/firestore';
import { db } from '../../firebase/config';
import AdminLayout from '../../components/AdminLayout';
import PageTitle from '../../components/PageTitle';
import LoadingSpinner from '../../components/LoadingSpinner';

export default function ManageFees() {
  const [fees, setFees] = useState([]); const [scholarships, setScholarships] = useState([]); const [loading, setLoading] = useState(true); const [form, setForm] = useState({ programme: '', admission: '', tuition: '', stationery: '' }); const [scholarship, setScholarship] = useState({ title: '', description: '' });
  const load = async () => { try { const [feeSnap, scholarshipSnap] = await Promise.all([getDocs(query(collection(db, 'admissionFees'), orderBy('programme', 'asc'))), getDocs(query(collection(db, 'scholarships'), orderBy('createdAt', 'desc')))]); setFees(feeSnap.docs.map((item) => ({ id: item.id, ...item.data() }))); setScholarships(scholarshipSnap.docs.map((item) => ({ id: item.id, ...item.data() }))); } catch (error) { console.error(error); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const add = async (event) => { event.preventDefault(); await addDoc(collection(db, 'admissionFees'), { ...form, createdAt: serverTimestamp() }); setForm({ programme: '', admission: '', tuition: '', stationery: '' }); load(); };
  const remove = async (id) => { await deleteDoc(doc(db, 'admissionFees', id)); setFees((items) => items.filter((item) => item.id !== id)); };
  const addScholarship = async (event) => { event.preventDefault(); await addDoc(collection(db, 'scholarships'), { ...scholarship, published: true, createdAt: serverTimestamp() }); setScholarship({ title: '', description: '' }); load(); };
  const removeScholarship = async (id) => { await deleteDoc(doc(db, 'scholarships', id)); setScholarships((items) => items.filter((item) => item.id !== id)); };
  return <AdminLayout><PageTitle>Admissions Fees & Scholarships</PageTitle><form onSubmit={add} className="mt-5 grid max-w-4xl gap-3 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-4"><input required placeholder="Programme" value={form.programme} onChange={(e) => setForm({ ...form, programme: e.target.value })} className="rounded-lg border p-3" /><input placeholder="Admission fee" value={form.admission} onChange={(e) => setForm({ ...form, admission: e.target.value })} className="rounded-lg border p-3" /><input placeholder="Tuition" value={form.tuition} onChange={(e) => setForm({ ...form, tuition: e.target.value })} className="rounded-lg border p-3" /><div className="flex gap-2"><input placeholder="Stationery" value={form.stationery} onChange={(e) => setForm({ ...form, stationery: e.target.value })} className="min-w-0 flex-1 rounded-lg border p-3" /><button className="rounded-full bg-primary px-4 text-sm font-bold text-white">Add</button></div></form><form onSubmit={addScholarship} className="mt-5 grid max-w-4xl gap-3 rounded-xl border border-blue-200 bg-blue-50 p-5 sm:grid-cols-[0.7fr_1.3fr_auto]"><input required placeholder="Scholarship title" value={scholarship.title} onChange={(e) => setScholarship({ ...scholarship, title: e.target.value })} className="rounded-lg border p-3" /><input required placeholder="Eligibility and application information" value={scholarship.description} onChange={(e) => setScholarship({ ...scholarship, description: e.target.value })} className="rounded-lg border p-3" /><button className="rounded-full bg-primary px-4 text-sm font-bold text-white">Add Scholarship</button></form><div className="mt-6 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <LoadingSpinner label="Loading fees" /> : <table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{['Programme', 'Admission', 'Tuition', 'Stationery', 'Actions'].map((heading) => <th key={heading} className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{fees.map((fee) => <tr key={fee.id}><td className="px-5 py-4 font-bold">{fee.programme}</td><td className="px-5 py-4">{fee.admission}</td><td className="px-5 py-4">{fee.tuition}</td><td className="px-5 py-4">{fee.stationery}</td><td className="px-5 py-4"><button onClick={() => remove(fee.id)} className="font-bold text-red-600">Delete</button></td></tr>)}</tbody></table>}</div><div className="mt-5 space-y-2">{scholarships.map((item) => <div key={item.id} className="flex justify-between rounded-lg bg-white p-4 shadow-sm"><span><strong>{item.title}:</strong> {item.description}</span><button onClick={() => removeScholarship(item.id)} className="ml-4 text-red-600">Delete</button></div>)}</div></AdminLayout>;
}
