import React, { useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp } from 'firebase/firestore';
import { deleteObject, getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import AdminLayout from '../../components/AdminLayout';
import PageTitle from '../../components/PageTitle';
import LoadingSpinner from '../../components/LoadingSpinner';
import { db, storage } from '../../firebase/config';

const initialForm = { title: '', category: 'Campus Life', order: 1, image: null };

export default function ManageGallery() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(initialForm); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = () => getDocs(query(collection(db, 'gallery'), orderBy('order', 'asc'))).then((snapshot) => setItems(snapshot.docs.map((item) => ({ id: item.id, ...item.data() })))).catch((error) => { console.error(error); setMessage('Unable to load gallery items.'); }).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); if (!form.image) return setMessage('Please choose an image.'); if (form.image.size > 180 * 1024) return setMessage('Gallery images must not exceed 180 KB.'); setSaving(true); setMessage(''); try { const path = `galleryImages/${Date.now()}-${form.image.name}`; const uploaded = await uploadBytes(ref(storage, path), form.image); const imageUrl = await getDownloadURL(uploaded.ref); await addDoc(collection(db, 'gallery'), { title: form.title.trim(), category: form.category, order: Number(form.order) || items.length + 1, published: true, imageUrl, imagePath: path, createdAt: serverTimestamp() }); setForm({ ...initialForm, order: items.length + 2 }); setMessage('Gallery image published successfully.'); await load(); } catch (error) { console.error(error); setMessage(error.message || 'Upload failed.'); } finally { setSaving(false); } };
  const remove = async (item) => { if (!window.confirm(`Remove "${item.title || 'this image'}" from the gallery?`)) return; await deleteDoc(doc(db, 'gallery', item.id)); if (item.imagePath) await deleteObject(ref(storage, item.imagePath)); setItems((current) => current.filter((entry) => entry.id !== item.id)); };
  return <AdminLayout><PageTitle>Gallery Manager</PageTitle><div className="mt-5 grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={submit} className="space-y-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-primary">Add Gallery Image</h2><label className="block text-sm font-bold text-darkgray">Caption<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="mt-2 w-full rounded-lg border border-slate-300 p-3" /></label><label className="block text-sm font-bold text-darkgray">Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3"><option>Campus Life</option><option>Academics</option><option>Sports</option><option>Arts &amp; Culture</option><option>Events</option></select></label><label className="block text-sm font-bold text-darkgray">Display order<input type="number" min="1" value={form.order} onChange={(e) => setForm({ ...form, order: e.target.value })} className="mt-2 w-full rounded-lg border border-slate-300 p-3" /></label><label className="block text-sm font-bold text-darkgray">Image <span className="font-normal text-slate-500">(maximum 180 KB)</span><input required type="file" accept="image/*" onChange={(e) => setForm({ ...form, image: e.target.files?.[0] || null })} className="mt-2 w-full rounded-lg border border-slate-300 p-2 text-sm" /></label><button disabled={saving} className="w-full rounded-full bg-primary px-5 py-3 text-sm font-bold text-white hover:bg-primary-dark disabled:opacity-60">{saving ? 'Uploading…' : 'Publish to Gallery'}</button>{message && <p role="status" className="text-sm font-semibold text-primary">{message}</p>}</form><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black text-primary">Published Gallery ({items.length})</h2><span className="text-xs font-bold text-slate-500">Ordered display</span></div>{loading ? <LoadingSpinner label="Loading gallery" /> : items.length === 0 ? <p className="rounded-lg bg-slate-50 p-8 text-center text-text-light">No gallery images yet.</p> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="overflow-hidden rounded-xl border border-slate-200 bg-slate-50"><img src={item.imageUrl} alt={item.title} className="h-36 w-full object-cover" loading="lazy" /><div className="p-3"><p className="text-[10px] font-black uppercase tracking-widest text-accent">{item.category} · #{item.order}</p><h3 className="mt-1 font-bold text-darkgray">{item.title}</h3><button onClick={() => remove(item)} className="mt-3 text-xs font-bold text-red-600 hover:underline">Remove image</button></div></article>)}</div>}</section></div></AdminLayout>;
}
