import React, { useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore';
import { db } from '../../firebase/config';
import AdminLayout from '../../components/AdminLayout';
import PageTitle from '../../components/PageTitle';
import LoadingSpinner from '../../components/LoadingSpinner';

export default function ManageAlerts() {
  const [alerts, setAlerts] = useState([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [form, setForm] = useState({ message: '', type: 'notice' });
  const load = () => getDocs(query(collection(db, 'schoolAlerts'), orderBy('createdAt', 'desc'))).then((snap) => setAlerts(snap.docs.map((item) => ({ id: item.id, ...item.data() })))).catch(console.error).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const add = async (event) => { event.preventDefault(); if (!form.message.trim()) return; await addDoc(collection(db, 'schoolAlerts'), { ...form, active: true, createdAt: serverTimestamp() }); setForm({ message: '', type: 'notice' }); setMessage('Alert published.'); load(); };
  const toggle = async (alert) => { await updateDoc(doc(db, 'schoolAlerts', alert.id), { active: !alert.active }); setAlerts((items) => items.map((item) => item.id === alert.id ? { ...item, active: !alert.active } : item)); };
  const remove = async (id) => { await deleteDoc(doc(db, 'schoolAlerts', id)); setAlerts((items) => items.filter((item) => item.id !== id)); };
  return <AdminLayout><PageTitle>School Alerts</PageTitle><form onSubmit={add} className="mt-5 flex max-w-3xl flex-col gap-3 rounded-xl border border-slate-200 bg-white p-5 sm:flex-row"><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} className="rounded-lg border border-slate-300 p-3"><option value="notice">Notice</option><option value="emergency">Emergency</option></select><input required value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Write an important school alert…" className="min-w-0 flex-1 rounded-lg border border-slate-300 p-3" /><button className="rounded-full bg-primary px-5 py-3 text-sm font-bold text-white hover:bg-primary-dark">Publish</button></form>{message && <p className="mt-3 text-sm font-semibold text-primary">{message}</p>}<div className="mt-6 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <LoadingSpinner label="Loading alerts" /> : <table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{['Message', 'Type', 'Status', 'Actions'].map((heading) => <th key={heading} className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{alerts.map((alert) => <tr key={alert.id}><td className="px-5 py-4 text-sm font-semibold">{alert.message}</td><td className="px-5 py-4 text-sm">{alert.type}</td><td className="px-5 py-4 text-sm">{alert.active ? 'Active' : 'Hidden'}</td><td className="space-x-3 px-5 py-4 text-sm"><button onClick={() => toggle(alert)} className="font-bold text-primary">{alert.active ? 'Hide' : 'Show'}</button><button onClick={() => remove(alert.id)} className="font-bold text-red-600">Delete</button></td></tr>)}</tbody></table>}</div></AdminLayout>;
}
